Update useTelegramMock.ts to prevent error
If you leave: 7.2 instead of latest

Error: Method "web_app_set_bottom_bar_color" is unsupported in Mini Apps version 7.2